### ISSUE TITLE
组件报错

### ISSUE THREAD

**Issue by cyrus-xc** [SuceV587/awesomewm-dot#1]
![5dbc50686e05605a3886b5321d0c124](https://github.com/SuceV587/awesomewm-dot/assets/59599375/5624710e-fc20-4e38-9deb-5577efa98463)

先是天气组件的报错，按照报错把天气107行注释掉之后天气好了, 然后开始报以上错误, 看起来是日历组件的问题。网上查错误信息只有一个帖子说组件可能没加layout，但我看是加了的，不清楚问题出在哪里。

环境是awesome4.3-5build1

**Comment by SuceV587** [comment]
尝试按照awesomewm的官方自己编译awesomewm试试。下载的awesomewm包经常有组件缺失

**Comment by cyrus-xc** [comment]
谢谢，之前是ubuntu/debian环境，重新装了arch并且本地编译awesome-git之后就好了

**Comment by SuceV587** [comment]
Done
